### ISSUE TITLE
Collapse sidebar

### ISSUE THREAD

**Issue by sewil** [sewil/org.onepace.web#8]

**Comment by GuyBransgrove** [comment]
![expanded](https://user-images.githubusercontent.com/6147955/40968387-c6b0f54c-68f8-11e8-98c4-1a24aaf4a14e.png)
![minimised](https://user-images.githubusercontent.com/6147955/40968389-c6ea2c2c-68f8-11e8-9778-0807389c6290.png)

Hey guys, I know I'm not assigned to this one so if @Jojoejoe3 already has a solution underway for this feel free to ignore mine.

I've included some screenshots of something for this that I threw together and before I potentially submit a PR I'd love some design feedback. Let me know what you think!
